### ISSUE TITLE
Compile

### ISSUE THREAD

**Issue by quexoo** [jwyce/Gungi#1]
Hi! Your game looks super awesome and I've wanted to play gungi for a really long time. I downloaded everything but I don't know how to compile the files so I can actually play. Can you explain how I can do that?

**Comment by jwyce** [comment]
Hello! I haven't really worked on this project in a while, but if you want
to play it or modify it you can import the source files into the eclipse
ide and run from there.
If you just want to play the game here's a link to download it -> download
gungi via mediafire
<http://www.mediafire.com/file/994eu828nmp8a0c/gungi.zip/file>
There might be some bugs, and I can't promise it'll be the best experience
but here ya go. :D

Best Regards,
*Jared Wyce*
Computer Science Student
Rutgers University


<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
